config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/site', as: 'rails_admin'
  root "inicio#index"
  devise_for :users
  namespace :admin do
    resources :contacts
  end
  #get 'doctor/eventdoctor'
  #get 'contact/contactus'
  #get 'service/detailevent'
  #get 'consult/event'
  #get 'team/detail'
  #get 'clinic/index4'
  #get 'about/index3'
  #get 'resultado/resultadoindex'
  get 'inicio/index'
  get 'agenda/index'
  get 'consultas/index'
  get 'equipe/index'
  get 'exames/index'
  get 'contato/index'
  get 'agenda/:id', to: "agenda#index"
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/contact.rb
class Admin::Contact < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clin_about.rb
class ClinAbout < ApplicationRecord
  has_one_attached :video #virtual não precisa estar no banco
end

app/models/clin_information.rb
class ClinInformation < ApplicationRecord
  has_one_attached :image #virtual não precisa estar no banco
  validates :title, presence: true,:allow_nil => false
	validates :description, presence: true,:allow_nil => false
	validates :image, presence: true,:allow_nil => false
end

app/models/lab_about.rb
class LabAbout < ApplicationRecord
  has_one_attached :video #virtual não precisa estar no banco
end

app/models/lab_information.rb
class LabInformation < ApplicationRecord
  # has_many_attached :image
  has_one_attached :image #virtual não precisa estar no banco
	validates :title, presence: true,:allow_nil => false
	validates :description, presence: true,:allow_nil => false
	validates :image, presence: true,:allow_nil => false

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum tipo: [:cliente, :admin]
  enum status: [:ativo, :inativo]
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  before_action :set_admin_contact, only: [:show, :edit, :update, :destroy]

  def index
    @admin_contacts = Admin::Contact.all
  end

  def show
  end

  def new
    @admin_contact = Admin::Contact.new
  end

  # def edit
  # end

  def create
    @admin_contact = Admin::Contact.new(admin_contact_params)
    respond_to do |format|
      if @admin_contact.save
        format.html { redirect_to @admin_contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @admin_contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update
  #   respond_to do |format|
  #     if @admin_contact.update(admin_contact_params)
  #       format.html { redirect_to @admin_contact, notice: 'Contact was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @admin_contact }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @admin_contact.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  def destroy
    @admin_contact.destroy
    respond_to do |format|
      format.html { redirect_to admin_contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_contact
      @admin_contact = Admin::Contact.find(params[:id])
    end

    def admin_contact_params
      params.require(:admin_contact).permit(:name, :email, :phone, :message)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def contactus
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/agenda_helper.rb
module AgendaHelper
end

app/helpers/clinic_helper.rb
module ClinicHelper
end

app/helpers/consult_helper.rb
module ConsultHelper
end

app/helpers/consultas_helper.rb
module ConsultasHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/equipe_helper.rb
module EquipeHelper
end

app/helpers/exames_helper.rb
module ExamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/resultado_helper.rb
module ResultadoHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/admin/contacts/_form.html.erb
<%= form_with(model: admin_contact, local: true) do |form| %>
  <% if admin_contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_contact.errors.count, "error") %> prohibited this admin_contact from being saved:</h2>

      <ul>
      <% admin_contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_field :message %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/contacts/edit.html.erb
<h1>Editing Admin Contact</h1>

<%= render 'form', admin_contact: @admin_contact %>

<%= link_to 'Show', @admin_contact %> |
<%= link_to 'Back', admin_contacts_path %>

app/views/admin/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_contacts.each do |admin_contact| %>
      <tr>
        <td><%= admin_contact.name %></td>
        <td><%= admin_contact.email %></td>
        <td><%= admin_contact.phone %></td>
        <td><%= admin_contact.message %></td>
        <td><%= link_to 'Show', admin_contact %></td>
        <td><%= link_to 'Edit', edit_admin_contact_path(admin_contact) %></td>
        <td><%= link_to 'Destroy', admin_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Contact', new_admin_contact_path %>

app/views/admin/contacts/new.html.erb
<h1>New Admin Contact</h1>

<%= render 'form', admin_contact: @admin_contact %>

<%= link_to 'Back', admin_contacts_path %>

app/views/admin/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin_contact.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @admin_contact.phone %>
</p>

<p>
  <strong>Message:</strong>
  <%= @admin_contact.message %>
</p>

<%= link_to 'Edit', edit_admin_contact_path(@admin_contact) %> |
<%= link_to 'Back', admin_contacts_path %>